"""
Pure Python DCF (Discounted Cash Flow) calculator.

No LLM calls - deterministic math only. The DCF agent provides assumptions;
this module runs the calculation.

Supports two modes:
1. Legacy: flat fcf_margin applied to revenue
2. Decomposed: full income-statement-driven FCF build with gross margins,
   opex, D&A, capex, NWC, and tax rate
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


# =============================================================================
# WACC Computation
# =============================================================================

# Default market assumptions
DEFAULT_RISK_FREE_RATE = 0.043   # 10Y Treasury ~4.3%
DEFAULT_EQUITY_RISK_PREMIUM = 0.055  # Long-run ERP ~5.5%
DEFAULT_BETA = 1.0


def compute_wacc(
    beta: Optional[float] = None,
    market_cap: Optional[float] = None,
    total_debt: Optional[float] = None,
    interest_expense: Optional[float] = None,
    tax_rate: float = 0.21,
    risk_free_rate: float = DEFAULT_RISK_FREE_RATE,
    equity_risk_premium: float = DEFAULT_EQUITY_RISK_PREMIUM,
) -> tuple[float, str]:
    """
    Compute WACC from CAPM components.

    Ke = Risk-free rate + Beta * ERP
    Kd = Interest expense / total debt * (1 - tax rate)
    WACC = Ke * (E/(D+E)) + Kd * (D/(D+E))

    Returns:
        (wacc, rationale_string)
    """
    beta_used = beta if beta and beta > 0 else DEFAULT_BETA

    # Cost of equity (CAPM)
    ke = risk_free_rate + beta_used * equity_risk_premium

    # Cost of debt
    kd = 0.0
    if total_debt and total_debt > 0 and interest_expense:
        kd_pretax = abs(interest_expense) / total_debt
        kd = kd_pretax * (1 - tax_rate)
    else:
        # Default assumption for investment-grade
        kd = risk_free_rate + 0.015  # 150bps spread
        kd = kd * (1 - tax_rate)

    # Capital structure weights
    equity = market_cap or 0
    debt = total_debt or 0
    total_capital = equity + debt

    if total_capital > 0:
        weight_equity = equity / total_capital
        weight_debt = debt / total_capital
    else:
        weight_equity = 1.0
        weight_debt = 0.0

    wacc = ke * weight_equity + kd * weight_debt

    # Clamp to reasonable range
    wacc = max(0.05, min(0.20, wacc))

    rationale = (
        f"WACC={wacc*100:.1f}%: Ke={ke*100:.1f}% (Rf={risk_free_rate*100:.1f}% + "
        f"Beta={beta_used:.2f} x ERP={equity_risk_premium*100:.1f}%), "
        f"Kd={kd*100:.1f}% after-tax, "
        f"E/(D+E)={weight_equity*100:.0f}%"
    )

    return wacc, rationale


def _pad_or_truncate(values: List[float], n: int, default: float = None) -> List[float]:
    """Pad a list to length n by repeating the last value, or truncate."""
    if not values:
        return [default or 0.0] * n
    if len(values) >= n:
        return list(values[:n])
    last = values[-1]
    return list(values) + [last] * (n - len(values))


@dataclass(frozen=True)
class DCFAssumptions:
    """Assumptions for a DCF model, typically generated by LLM.

    Supports both legacy (flat fcf_margin) and decomposed margin models.
    If gross_margins is provided, the decomposed model is used.
    """
    revenue_growth_rates: List[float]   # e.g. [0.12, 0.10, 0.08, 0.06, 0.04]
    wacc: float                          # e.g. 0.095
    terminal_growth_rate: float          # e.g. 0.025
    projection_years: int = 5

    # Legacy: single flat FCF margin
    fcf_margin: float = 0.0

    # Decomposed margin model (optional - used when gross_margins is provided)
    gross_margins: Optional[List[float]] = None        # per-year gross margin
    opex_as_pct_revenue: Optional[List[float]] = None  # SG&A + R&D as % revenue
    da_as_pct_revenue: float = 0.0                     # D&A as % revenue (stable)
    sbc_as_pct_revenue: float = 0.0                    # SBC as % revenue
    capex_as_pct_revenue: Optional[List[float]] = None # per-year capex intensity
    nwc_change_pct: float = 0.0                        # NWC as % of revenue delta
    tax_rate: float = 0.21                             # Effective tax rate

    # LLM rationale strings (for frontend tooltips)
    revenue_growth_rationale: str = ""
    fcf_margin_rationale: str = ""
    margin_rationale: str = ""
    wacc_rationale: str = ""
    terminal_growth_rationale: str = ""

    @property
    def is_decomposed(self) -> bool:
        """True if decomposed margin model should be used."""
        return self.gross_margins is not None and len(self.gross_margins) > 0

    def to_dict(self) -> Dict:
        result = {
            "revenue_growth_rates": list(self.revenue_growth_rates),
            "wacc": self.wacc,
            "terminal_growth_rate": self.terminal_growth_rate,
            "projection_years": self.projection_years,
            "revenue_growth_rationale": self.revenue_growth_rationale,
            "wacc_rationale": self.wacc_rationale,
            "terminal_growth_rationale": self.terminal_growth_rationale,
        }
        if self.is_decomposed:
            result.update({
                "gross_margins": list(self.gross_margins) if self.gross_margins else [],
                "opex_as_pct_revenue": list(self.opex_as_pct_revenue) if self.opex_as_pct_revenue else [],
                "da_as_pct_revenue": self.da_as_pct_revenue,
                "sbc_as_pct_revenue": self.sbc_as_pct_revenue,
                "capex_as_pct_revenue": list(self.capex_as_pct_revenue) if self.capex_as_pct_revenue else [],
                "nwc_change_pct": self.nwc_change_pct,
                "tax_rate": self.tax_rate,
                "margin_rationale": self.margin_rationale,
            })
        else:
            result["fcf_margin"] = self.fcf_margin
            result["fcf_margin_rationale"] = self.fcf_margin_rationale
        return result


@dataclass(frozen=True)
class DCFProjectionYear:
    """Detailed projection for a single year in the decomposed model."""
    year: int
    revenue: float
    gross_profit: float
    opex: float
    ebitda: float
    da: float
    ebit: float
    nopat: float
    capex: float
    nwc_change: float
    sbc: float
    fcf: float
    discounted_fcf: float


@dataclass(frozen=True)
class DCFResult:
    """Complete DCF valuation output."""
    base_revenue: float
    projected_revenues: List[float]
    projected_fcfs: List[float]
    discounted_fcfs: List[float]
    terminal_value: float
    pv_terminal_value: float
    enterprise_value: float
    net_debt: float
    equity_value: float
    shares_outstanding: float
    fair_value_per_share: float
    current_price: float
    upside_downside_pct: float
    assumptions: DCFAssumptions
    # Detailed year-by-year projections (only for decomposed model)
    projection_details: List[DCFProjectionYear] = field(default_factory=list)

    def to_dict(self) -> Dict:
        result = {
            "fair_value_per_share": self.fair_value_per_share,
            "current_price": self.current_price,
            "upside_downside_pct": self.upside_downside_pct,
            "enterprise_value": self.enterprise_value,
            "equity_value": self.equity_value,
            "base_revenue": self.base_revenue,
            "projected_revenues": self.projected_revenues,
            "projected_fcfs": self.projected_fcfs,
            "discounted_fcfs": self.discounted_fcfs,
            "terminal_value": self.terminal_value,
            "pv_terminal_value": self.pv_terminal_value,
            "net_debt": self.net_debt,
            "shares_outstanding": self.shares_outstanding,
            "assumptions": self.assumptions.to_dict(),
        }
        if self.projection_details:
            result["projection_details"] = [
                {
                    "year": d.year, "revenue": d.revenue,
                    "gross_profit": d.gross_profit, "opex": d.opex,
                    "ebitda": d.ebitda, "da": d.da, "ebit": d.ebit,
                    "nopat": d.nopat, "capex": d.capex,
                    "nwc_change": d.nwc_change, "sbc": d.sbc,
                    "fcf": d.fcf, "discounted_fcf": d.discounted_fcf,
                }
                for d in self.projection_details
            ]
        return result


def calculate_dcf(
    base_revenue: float,
    net_debt: float,
    shares_outstanding: float,
    current_price: float,
    assumptions: DCFAssumptions,
) -> DCFResult:
    """
    Run a DCF calculation.

    If assumptions.is_decomposed is True, uses the full income-statement-driven
    FCF build. Otherwise falls back to the legacy flat FCF margin approach.
    """
    if assumptions.is_decomposed:
        return _calculate_dcf_decomposed(base_revenue, net_debt, shares_outstanding, current_price, assumptions)
    return _calculate_dcf_legacy(base_revenue, net_debt, shares_outstanding, current_price, assumptions)


def _calculate_dcf_legacy(
    base_revenue: float,
    net_debt: float,
    shares_outstanding: float,
    current_price: float,
    assumptions: DCFAssumptions,
) -> DCFResult:
    """Legacy DCF: flat FCF margin applied to projected revenue."""
    n = assumptions.projection_years
    growth_rates = _pad_or_truncate(assumptions.revenue_growth_rates, n, 0.03)

    # Project revenues
    projected_revenues = []
    rev = base_revenue
    for rate in growth_rates:
        rev = rev * (1 + rate)
        projected_revenues.append(rev)

    # Apply FCF margin
    projected_fcfs = [rev * assumptions.fcf_margin for rev in projected_revenues]

    # Discount FCFs
    discounted_fcfs = []
    for i, fcf in enumerate(projected_fcfs):
        discount_factor = (1 + assumptions.wacc) ** (i + 1)
        discounted_fcfs.append(fcf / discount_factor)

    # Terminal value (Gordon Growth Model)
    final_fcf = projected_fcfs[-1]
    terminal_value = final_fcf * (1 + assumptions.terminal_growth_rate) / (
        assumptions.wacc - assumptions.terminal_growth_rate
    )

    pv_terminal_value = terminal_value / ((1 + assumptions.wacc) ** n)
    enterprise_value = sum(discounted_fcfs) + pv_terminal_value
    equity_value = enterprise_value - net_debt
    fair_value_per_share = equity_value / shares_outstanding if shares_outstanding > 0 else 0

    upside_downside_pct = (
        ((fair_value_per_share / current_price) - 1) * 100
        if current_price > 0
        else 0
    )

    return DCFResult(
        base_revenue=base_revenue,
        projected_revenues=projected_revenues,
        projected_fcfs=projected_fcfs,
        discounted_fcfs=discounted_fcfs,
        terminal_value=terminal_value,
        pv_terminal_value=pv_terminal_value,
        enterprise_value=enterprise_value,
        net_debt=net_debt,
        equity_value=equity_value,
        shares_outstanding=shares_outstanding,
        fair_value_per_share=fair_value_per_share,
        current_price=current_price,
        upside_downside_pct=upside_downside_pct,
        assumptions=assumptions,
    )


def _calculate_dcf_decomposed(
    base_revenue: float,
    net_debt: float,
    shares_outstanding: float,
    current_price: float,
    assumptions: DCFAssumptions,
) -> DCFResult:
    """
    Decomposed DCF: full income-statement-driven FCF build.

    FCF = NOPAT + D&A - CapEx - delta_NWC + SBC add-back
    Where:
      Revenue = base * (1 + growth)
      Gross Profit = Revenue * gross_margin
      EBITDA = Gross Profit - OpEx
      EBIT = EBITDA - D&A
      NOPAT = EBIT * (1 - tax_rate)
      FCF = NOPAT + D&A - CapEx - delta_NWC + SBC
    """
    n = assumptions.projection_years
    growth_rates = _pad_or_truncate(assumptions.revenue_growth_rates, n, 0.03)
    gross_margins = _pad_or_truncate(assumptions.gross_margins or [], n, 0.50)
    opex_pcts = _pad_or_truncate(assumptions.opex_as_pct_revenue or [], n, 0.20)
    capex_pcts = _pad_or_truncate(assumptions.capex_as_pct_revenue or [], n, 0.05)

    projected_revenues = []
    projected_fcfs = []
    discounted_fcfs = []
    projection_details = []

    prev_revenue = base_revenue

    for i in range(n):
        # Revenue
        revenue = prev_revenue * (1 + growth_rates[i])

        # Gross Profit
        gross_profit = revenue * gross_margins[i]

        # OpEx (SG&A + R&D as % of revenue)
        opex = revenue * opex_pcts[i]

        # EBITDA = Gross Profit - OpEx
        ebitda = gross_profit - opex

        # D&A
        da = revenue * assumptions.da_as_pct_revenue

        # EBIT = EBITDA - D&A
        ebit = ebitda - da

        # NOPAT = EBIT * (1 - tax)
        nopat = ebit * (1 - assumptions.tax_rate)

        # CapEx
        capex = revenue * capex_pcts[i]

        # NWC change (% of revenue delta)
        revenue_delta = revenue - prev_revenue
        nwc_change = revenue_delta * assumptions.nwc_change_pct

        # SBC add-back (non-cash expense already deducted from NOPAT through OpEx,
        # but conventionally added back for UFCF)
        sbc = revenue * assumptions.sbc_as_pct_revenue

        # FCF = NOPAT + D&A - CapEx - delta_NWC + SBC add-back
        fcf = nopat + da - capex - nwc_change + sbc

        # Discount
        discount_factor = (1 + assumptions.wacc) ** (i + 1)
        discounted_fcf = fcf / discount_factor

        projected_revenues.append(revenue)
        projected_fcfs.append(fcf)
        discounted_fcfs.append(discounted_fcf)

        projection_details.append(DCFProjectionYear(
            year=i + 1,
            revenue=revenue,
            gross_profit=gross_profit,
            opex=opex,
            ebitda=ebitda,
            da=da,
            ebit=ebit,
            nopat=nopat,
            capex=capex,
            nwc_change=nwc_change,
            sbc=sbc,
            fcf=fcf,
            discounted_fcf=discounted_fcf,
        ))

        prev_revenue = revenue

    # Terminal value
    final_fcf = projected_fcfs[-1]
    terminal_value = final_fcf * (1 + assumptions.terminal_growth_rate) / (
        assumptions.wacc - assumptions.terminal_growth_rate
    )
    pv_terminal_value = terminal_value / ((1 + assumptions.wacc) ** n)

    enterprise_value = sum(discounted_fcfs) + pv_terminal_value
    equity_value = enterprise_value - net_debt
    fair_value_per_share = equity_value / shares_outstanding if shares_outstanding > 0 else 0

    upside_downside_pct = (
        ((fair_value_per_share / current_price) - 1) * 100
        if current_price > 0
        else 0
    )

    return DCFResult(
        base_revenue=base_revenue,
        projected_revenues=projected_revenues,
        projected_fcfs=projected_fcfs,
        discounted_fcfs=discounted_fcfs,
        terminal_value=terminal_value,
        pv_terminal_value=pv_terminal_value,
        enterprise_value=enterprise_value,
        net_debt=net_debt,
        equity_value=equity_value,
        shares_outstanding=shares_outstanding,
        fair_value_per_share=fair_value_per_share,
        current_price=current_price,
        upside_downside_pct=upside_downside_pct,
        assumptions=assumptions,
        projection_details=projection_details,
    )
