"""
Bull/Base/Bear Scenario Modeling.

Runs three full DCF models with probability-weighted fair value.
Pure math - no LLM calls. The DCF agent or a separate scenario agent
provides the three assumption sets.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from src_george_researcher.valuation.dcf_engine import (
    DCFAssumptions,
    DCFResult,
    calculate_dcf,
)


@dataclass(frozen=True)
class ScenarioCase:
    """A single scenario with its assumptions, result, and probability."""
    name: str            # "Bull", "Base", "Bear"
    probability: float   # e.g. 0.25
    assumptions: DCFAssumptions
    result: DCFResult


@dataclass(frozen=True)
class ScenarioResult:
    """Complete scenario modeling output."""
    bull: ScenarioCase
    base: ScenarioCase
    bear: ScenarioCase
    weighted_fair_value: float
    current_price: float
    weighted_upside_pct: float

    def to_dict(self) -> Dict:
        def _case_dict(case: ScenarioCase) -> Dict:
            return {
                "name": case.name,
                "probability": case.probability,
                "fair_value": case.result.fair_value_per_share,
                "upside_pct": case.result.upside_downside_pct,
                "revenue_yr5": case.result.projected_revenues[-1] if case.result.projected_revenues else 0,
                "assumptions": case.assumptions.to_dict(),
            }
        return {
            "bull": _case_dict(self.bull),
            "base": _case_dict(self.base),
            "bear": _case_dict(self.bear),
            "weighted_fair_value": self.weighted_fair_value,
            "current_price": self.current_price,
            "weighted_upside_pct": self.weighted_upside_pct,
        }


def run_scenarios(
    base_revenue: float,
    net_debt: float,
    shares_outstanding: float,
    current_price: float,
    base_assumptions: DCFAssumptions,
    bull_assumptions: Optional[DCFAssumptions] = None,
    bear_assumptions: Optional[DCFAssumptions] = None,
    probabilities: tuple = (0.25, 0.50, 0.25),
) -> ScenarioResult:
    """
    Run bull/base/bear scenario analysis.

    If bull/bear assumptions are not provided, they are automatically
    generated by shifting the base case growth and margins.

    Args:
        base_revenue: Most recent annual revenue
        net_debt: Total debt - cash
        shares_outstanding: Diluted shares
        current_price: Current stock price
        base_assumptions: Base case DCF assumptions
        bull_assumptions: Optional bull case (auto-generated if None)
        bear_assumptions: Optional bear case (auto-generated if None)
        probabilities: (bull_prob, base_prob, bear_prob) must sum to 1.0

    Returns:
        ScenarioResult with three cases and weighted fair value
    """
    p_bull, p_base, p_bear = probabilities

    # Auto-generate bull/bear if not provided
    if bull_assumptions is None:
        bull_assumptions = _generate_bull_case(base_assumptions)
    if bear_assumptions is None:
        bear_assumptions = _generate_bear_case(base_assumptions)

    # Run all three DCFs
    base_result = calculate_dcf(base_revenue, net_debt, shares_outstanding, current_price, base_assumptions)
    bull_result = calculate_dcf(base_revenue, net_debt, shares_outstanding, current_price, bull_assumptions)
    bear_result = calculate_dcf(base_revenue, net_debt, shares_outstanding, current_price, bear_assumptions)

    # Weighted fair value
    weighted_fv = (
        p_bull * bull_result.fair_value_per_share +
        p_base * base_result.fair_value_per_share +
        p_bear * bear_result.fair_value_per_share
    )

    weighted_upside = ((weighted_fv / current_price) - 1) * 100 if current_price > 0 else 0

    return ScenarioResult(
        bull=ScenarioCase("Bull", p_bull, bull_assumptions, bull_result),
        base=ScenarioCase("Base", p_base, base_assumptions, base_result),
        bear=ScenarioCase("Bear", p_bear, bear_assumptions, bear_result),
        weighted_fair_value=weighted_fv,
        current_price=current_price,
        weighted_upside_pct=weighted_upside,
    )


def _generate_bull_case(base: DCFAssumptions) -> DCFAssumptions:
    """Generate optimistic scenario by boosting growth and margins."""
    # Boost growth rates by ~30% relative
    bull_growth = [min(0.50, r * 1.3 + 0.02) for r in base.revenue_growth_rates]

    if base.is_decomposed:
        # Expand margins
        bull_gross = [min(0.95, m + 0.02) for m in (base.gross_margins or [])] or None
        bull_opex = [max(0.05, o - 0.02) for o in (base.opex_as_pct_revenue or [])] or None
        bull_capex = [max(0.01, c - 0.005) for c in (base.capex_as_pct_revenue or [])] or None

        return DCFAssumptions(
            revenue_growth_rates=bull_growth,
            wacc=max(0.05, base.wacc - 0.005),
            terminal_growth_rate=min(base.wacc - 0.02, base.terminal_growth_rate + 0.005),
            projection_years=base.projection_years,
            gross_margins=bull_gross,
            opex_as_pct_revenue=bull_opex,
            da_as_pct_revenue=base.da_as_pct_revenue,
            sbc_as_pct_revenue=base.sbc_as_pct_revenue,
            capex_as_pct_revenue=bull_capex,
            nwc_change_pct=base.nwc_change_pct,
            tax_rate=base.tax_rate,
            revenue_growth_rationale="Bull case: accelerated growth from market share gains and new product adoption.",
            margin_rationale="Bull case: margin expansion from operating leverage and pricing power.",
        )
    else:
        return DCFAssumptions(
            revenue_growth_rates=bull_growth,
            fcf_margin=min(0.80, base.fcf_margin * 1.15 + 0.02),
            wacc=max(0.05, base.wacc - 0.005),
            terminal_growth_rate=min(base.wacc - 0.02, base.terminal_growth_rate + 0.005),
            projection_years=base.projection_years,
            revenue_growth_rationale="Bull case: accelerated growth.",
            fcf_margin_rationale="Bull case: margin expansion from operating leverage.",
        )


def _generate_bear_case(base: DCFAssumptions) -> DCFAssumptions:
    """Generate pessimistic scenario by cutting growth and margins."""
    bear_growth = [max(-0.30, r * 0.6 - 0.02) for r in base.revenue_growth_rates]

    if base.is_decomposed:
        bear_gross = [max(0.0, m - 0.03) for m in (base.gross_margins or [])] or None
        bear_opex = [min(0.80, o + 0.03) for o in (base.opex_as_pct_revenue or [])] or None
        bear_capex = [min(0.25, c + 0.01) for c in (base.capex_as_pct_revenue or [])] or None

        return DCFAssumptions(
            revenue_growth_rates=bear_growth,
            wacc=min(0.20, base.wacc + 0.01),
            terminal_growth_rate=max(0.005, base.terminal_growth_rate - 0.005),
            projection_years=base.projection_years,
            gross_margins=bear_gross,
            opex_as_pct_revenue=bear_opex,
            da_as_pct_revenue=base.da_as_pct_revenue,
            sbc_as_pct_revenue=base.sbc_as_pct_revenue,
            capex_as_pct_revenue=bear_capex,
            nwc_change_pct=base.nwc_change_pct,
            tax_rate=base.tax_rate,
            revenue_growth_rationale="Bear case: growth deceleration from competitive pressure and market saturation.",
            margin_rationale="Bear case: margin compression from pricing pressure and rising costs.",
        )
    else:
        return DCFAssumptions(
            revenue_growth_rates=bear_growth,
            fcf_margin=max(-0.50, base.fcf_margin * 0.75 - 0.02),
            wacc=min(0.20, base.wacc + 0.01),
            terminal_growth_rate=max(0.005, base.terminal_growth_rate - 0.005),
            projection_years=base.projection_years,
            revenue_growth_rationale="Bear case: growth deceleration.",
            fcf_margin_rationale="Bear case: margin compression.",
        )


def format_scenarios_markdown(result: ScenarioResult) -> str:
    """Format scenario analysis as markdown."""
    lines = [
        "**Scenario Analysis: Bull / Base / Bear**\n",
        f"**Probability-Weighted Fair Value: ${result.weighted_fair_value:.2f}** "
        f"({'Upside' if result.weighted_upside_pct > 0 else 'Downside'}: "
        f"{abs(result.weighted_upside_pct):.1f}% from ${result.current_price:.2f})\n",
        "| Scenario | Probability | Fair Value | Upside/Downside | Year 5 Revenue |",
        "|---|---|---|---|---|",
    ]

    for case in [result.bull, result.base, result.bear]:
        rev5 = case.result.projected_revenues[-1] / 1e9 if case.result.projected_revenues else 0
        lines.append(
            f"| **{case.name}** | {case.probability*100:.0f}% | "
            f"${case.result.fair_value_per_share:.2f} | "
            f"{case.result.upside_downside_pct:+.1f}% | "
            f"${rev5:.1f}B |"
        )

    return "\n".join(lines)
